Add applying new yaml file to the workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -24,17 +24,6 @@ jobs:
       - name: Generate Kubernetes Manifest
         run: |
           make generate-kubernetes-manifests
-          ls
-          pwd
-#          helm repo add opentelemetry-collector https://open-telemetry.github.io/opentelemetry-helm-charts
-#          helm repo update
-#          helm dependency build ./charts/opentelemetry-demo
-#
-#          helm template opentelemetry-demo ./charts/opentelemetry-demo \
-#            --namespace otel-demo \
-#            --set image.repository=ghcr.io/shareefm0/demo \
-#            --set image.tag=latest \
-#            > opentelemetry-demo.yaml
 
       - name: Copy Manifest to EC2 Instance
         uses: appleboy/scp-action@v0.1.2
@@ -45,45 +34,45 @@ jobs:
           source: './kubernetes/opentelemetry-demo.yaml'
           target: '/home/ec2-user/'
 
-#      - name: Apply Manifest Using Kubectl on EC2
-#        uses: appleboy/ssh-action@v0.1.3
-#        with:
-#          host: ${{ secrets.EC2_HOST }}
-#          username: ec2-user
-#          key: ${{ secrets.EC2_SSH_KEY }}
-#          script: |
-#            # Backup existing manifest
-#            if [ -f /home/ec2-user/opentelemetry-demo.yaml ]; then
-#              cp /home/ec2-user/opentelemetry-demo.yaml /home/ec2-user/opentelemetry-demo-backup.yaml
-#            fi
-#
-#            # Apply new manifest
-#            kubectl apply -f /home/ec2-user/opentelemetry-demo.yaml
-#
-#            # Wait for deployment to complete
-#            kubectl rollout status deployment/frontend -n otel-demo --timeout=300s
-#
-#      - name: Monitor Deployment and Rollback if Necessary
-#        uses: appleboy/ssh-action@v0.1.3
-#        with:
-#          host: ${{ secrets.EC2_HOST }}
-#          username: ec2-user
-#          key: ${{ secrets.EC2_SSH_KEY }}
-#          script: |
-#            # Wait for 5 minutes
-#            sleep 300
-#
-#            # Check for unhealthy pods
-#            UNHEALTHY_PODS=$(kubectl get pods -n otel-demo --field-selector=status.phase!=Running --no-headers | wc -l)
-#            if [ "$UNHEALTHY_PODS" -ne 0 ]; then
-#              echo "Detected issues with deployment. Rolling back..."
-#              # Restore previous manifest
-#              if [ -f /home/ec2-user/opentelemetry-demo-backup.yaml ]; then
-#                kubectl apply -f /home/ec2-user/opentelemetry-demo-backup.yaml
-#              else
-#                echo "No backup manifest found. Cannot rollback."
-#                exit 1
-#              fi
-#            else
-#              echo "Deployment is healthy."
-#            fi
+      - name: Apply Manifest Using Kubectl on EC2
+        uses: appleboy/ssh-action@v0.1.3
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ec2-user
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            # Backup existing manifest
+            if [ -f /home/ec2-user/opentelemetry-demo.yaml ]; then
+              cp /home/ec2-user/kubernetes/opentelemetry-demo.yaml /home/ec2-user/kubernetes/opentelemetry-demo-backup.yaml
+            fi
+
+            # Apply new manifest
+            KUBECONFIG="/home/ec2-user/.kube/config" kubectl apply --namespace otel-demo -f /home/ec2-user/kubernetes/opentelemetry-demo.yaml
+
+            # Wait for deployment to complete
+            KUBECONFIG="/home/ec2-user/.kube/config" kubectl rollout status deployment/frontend -n otel-demo --timeout=30s
+
+      - name: Monitor Deployment and Rollback if Necessary
+        uses: appleboy/ssh-action@v0.1.3
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ec2-user
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            # Wait for 5 minutes
+            sleep 30
+
+            # Check for unhealthy pods
+            UNHEALTHY_PODS=$(kubectl get pods -n otel-demo --field-selector=status.phase!=Running --no-headers | wc -l)
+            if [ "$UNHEALTHY_PODS" -ne 0 ]; then
+              echo "Detected issues with deployment. Rolling back..."
+              # Restore previous manifest
+              if [ -f /home/ec2-user/opentelemetry-demo-backup.yaml ]; then
+                kubectl apply -f /home/ec2-user/opentelemetry-demo-backup.yaml
+              else
+                echo "No backup manifest found. Cannot rollback."
+                exit 1
+              fi
+            else
+              echo "Deployment is healthy."
+            fi
